name: docs

on:
  push:
    branches: master
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Install dependencies for Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      working-directory: ./docs
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - run: poetry install
    - name: Docs
      working-directory: ./docs
      run: |
        poetry run ./mkdocs.sh
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./docs/_build/html # The folder the action should deploy.
